baseURL = 'https://noahhefner.info'
languageCode = 'en-us'
title = 'Noah Hefner'
theme = 'hugo-theme-m10c'

 [params]
  author = "Noah Hefner"
  description = "Software Engineer"
  avatar = "images/avatar.jpg"
  menu_item_separator = " | "
  [params.style]
    lightColor = "#c9c9c9"
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightestColor = "#ffffff"
    primaryColor = "#57cc8a"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/noahhefner"
  [[params.social]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/nhefner"
